version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - ./prisma:/app/prisma
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=devlab-secret-key-change-in-production
      - DOCKER_HOST=unix:///var/run/docker.sock
    depends_on:
      - db-setup
    privileged: true  # Required for Docker operations

  db-setup:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/app
      - ./prisma:/app/prisma
    environment:
      - DATABASE_URL=file:./dev.db
    command: ["sh", "-c", "npx prisma db push && npx tsx src/seed.ts"]

volumes:
  db_data: